Tournaments/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from viewer.views import TournamentsIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('viewer/', include('viewer.urls')),
    path('', TournamentsIndexView.as_view(), name="index"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/urls.py
from django.urls import path

from viewer.views import TeamCreateView, TeamsView, TeamDeleteView, TournamentsIndexView, PlayerCreateView, PlayersView, \
    PlayerDeleteView, TournamentCreateView, TournamentsView, TournamentDeleteView

app_name = 'viewer'
urlpatterns = [
    path('', TournamentsIndexView.as_view(), name="index"),
    path('create_team', TeamCreateView.as_view(), name="create_team"),
    path('teams', TeamsView.as_view(), name="teams"),
    path('team/<int:pk>/delete', TeamDeleteView.as_view(), name="delete_team"),
    path('create_player', PlayerCreateView.as_view(), name="create_player"),
    path('players', PlayersView.as_view(), name="players"),
    path('player/<int:pk>/delete', PlayerDeleteView.as_view(), name="delete_player"),
    path('create_tournament', TournamentCreateView.as_view(), name="create_tournament"),
    path('tournaments', TournamentsView.as_view(), name="tournaments"),
    path('player/<int:pk>/tournament', TournamentDeleteView.as_view(), name="delete_tournament"),
]

viewer/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=40)
    image = models.ImageField(upload_to="team_pics")

    def __str__(self):
        return f'{self.name}'


class Player(models.Model):
    name = models.CharField(max_length=40)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    avatar = models.ImageField(default="player_pics/avatar.png", upload_to='player_pics')
    def __str__(self):
        return f'{self.name}'


class Tournament(models.Model):
    players = models.ManyToManyField(Player, blank=True, null=True)

viewer/forms.py
from django.forms import ModelForm

from viewer.models import Team, Player, Tournament


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = '__all__'
        labels = {
            'user_id': 'User',
            'name': 'Nazwa',
            'image': 'Zdjęcie',
        }


class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = '__all__'
        labels = {
            'name': 'Nazwa',
            'avatar': 'Zdjęcie',
        }


class TournamentForm(ModelForm):
    class Meta:
        model = Tournament
        fields = '__all__'

viewer/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView

from viewer.forms import TeamForm
from viewer.models import Tournament, Team, Player
from viewer.templates.functions import pairs


class TournamentsIndexView(ListView):
    template_name = "tournaments_index.html"
    model = Tournament


class TeamCreateView(CreateView):
    template_name = 'forms/form.html'
    form_class = TeamForm
    success_url = reverse_lazy('viewer:teams')


class TeamsView(ListView):
    template_name = "teams.html"
    model = Team
    paginate_by = 10


class TeamDeleteView(DeleteView):
    template_name = "forms/team_delete_form.html"
    model = Team
    success_url = reverse_lazy('viewer:teams')


class PlayerCreateView(CreateView):
    template_name = "forms/form.html"
    model = Player
    success_url = reverse_lazy('viewer:players')
    fields = '__all__'


class PlayersView(ListView):
    template_name = "players.html"
    model = Player
    paginate_by = 10


class PlayerDeleteView(DeleteView):
    template_name = "forms/team_delete_form.html"
    model = Player
    success_url = reverse_lazy('viewer:players')


class TournamentCreateView(CreateView):
    template_name = "forms/form.html"
    model = Tournament
    success_url = reverse_lazy('viewer:index')
    fields = '__all__'


class TournamentsView(ListView):
    template_name = "tournaments.html"
    model = Tournament

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['players_list'] = Player.objects.all()

        pairs(context)


        return context

class TournamentDeleteView(DeleteView):
    template_name = "forms/team_delete_form.html"
    model = Tournament
    success_url = reverse_lazy('viewer:tournaments')

viewer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tournaments </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
    div.card {
  margin: 25px;
  background-color: rgba(230, 230, 230, 0.4) !important;
  font-family:'Courier New';
  display: block;
  margin-left: auto;
  margin-right: auto;
}

        div {text-align: center;}
        label, h1, h3, h2, table tr td, table tr th{
    background-color: rgba(230, 230, 230, 0.2) !important;
            color: white;
            margin: 20px;
            font-family:'Courier New';
}

    body {
            background-image: url("{% static "viewer\background.jpg" %}");
              background-attachment: fixed;
            background-size: cover;
}

.container {
  height: 50rem;
  position: relative;
}

.center {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}


    </style>

    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
<nav style="font-family:'Courier New'" class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
  <a style="margin-left:20px" class="navbar-brand" href="{% url 'index' %}">Tournaments</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'viewer:create_tournament' %}"{% url 'viewer:players' %}"">Nowy turniej <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'viewer:tournaments' %}">Turnieje</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'viewer:players' %}">Gracze</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'viewer:teams' %}">Zespoły</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  {% block content %}
  {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

viewer/templates/forms/form.html
{% extends "base.html" %}


{% block content %}
    <form method="post" enctype="multipart/form-data" class="py-4" style="max-width: 30%; margin:auto;">
        {% csrf_token %}
        {% include "forms/form_base_bs5.html" %}
        <button type="submit" style="font-family:'Courier New'" class="btn btn-secondary">Dodaj</button>
    </form>
{% endblock %}

viewer/templates/forms/form_base_bs5.html
{% load widget_tweaks %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </div>
    {% endif %}

    {% for hidden_field in form.hidden_fields %}
        {% if hidden_field.errors %}
            {% for error in hidden_field.errors %}
                <li>{{ hidden_field.name }} - {{ error }}</li>
            {% endfor %}
        {% endif %}
        {{ hidden_field }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group mb-3">
      <label for="{{ field.id_for_label }}" class="form-label rounded py-1 px-1 text-center">{{ field.label }}</label>
      {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
          {% else %}
              {% render_field field class="form-control is-valid" %}
          {% endif %}
      {% else %}
          {% render_field field class="form-control" %}
      {% endif %}
      {% if field.help_text %}
            <small class="form-text text-muted mb-3">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

viewer/templates/forms/team_delete_form.html
{% extends "base.html" %}

{% block content %}
<form method="post" class="py-4">
{% csrf_token %}
<h3>
    Are you sure you want to remove {{ object.name }} from the database?
</h3>
<input type="submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

viewer/templates/players.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'viewer:create_player' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">+</a>
{% for player in object_list %}
<div class="card" style="width: 18rem;">
  <img style="width:150px; height:150px" class="card-img-top-center" src={{ player.avatar.url }} alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{player.name}}</h5>
    <h5 class="card-title">{{player.team}}</h5>
    <img style="width:5rem; height:5rem" class="card-img-top-center" src={{ player.team.image.url }} alt="Card image cap">

    <a href="{% url "viewer:delete_player" player.id %}" class="btn btn-primary">Delete</a>
  </div>
</div>
{% endfor %}
{% endblock %}

viewer/templates/teams.html
{% extends "base.html" %}

{% block content %}


<table class="table table-light table-hover"  style="margin-top: 40px;">
  <thead class="thead-light">
  <tr>
    <th colspan="9" style="font-size: large;">Dostępne zespoły <a href="{% url 'viewer:create_team' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">+</a></th>
  </tr>
    <tr>
      <th scope="col">Nazwa</th>
      <th scope="col">Logo</th>

    </tr>
  </thead>
  <tbody>
  {% for team in object_list %}
    <tr>
      <td>{{ team.name}} </td>
      <td><img style="width:100px; height:100px" src="{{ team.image.url }}"> <a class="btn btn-danger btn-sm float-end " href="{% url "viewer:delete_team" team.id %}">X</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-secondary mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <a class="btn btn-outline-secondary disabled mb-4" href="#">First</a>
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <a class="btn btn-outline-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% else %}
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Next</a>
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Last</a>
        {% endif %}

    {% endif %}
{% endblock %}

viewer/templates/tournaments.html
{% extends "base.html" %}

{% block content %}


<table class="table table-light table-hover"  style="margin-top: 40px;">
  <thead class="thead-light">
  <tr>
    <th colspan="9" style="font-size: large;">Turnieje</th>
  </tr>
    <tr>
      <th scope="col">Gracze</th>

    </tr>
  </thead>
  <tbody>
  {% for tournament in object_list %}
    <tr>
        <td>
        {% for player in tournament.players.all %}
      {{ player }}
        {% endfor %}
             <a class="btn btn-danger btn-sm float-end " href="{% url "viewer:delete_tournament" tournament.id %}">X</a>
        </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-secondary mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <a class="btn btn-outline-secondary disabled mb-4" href="#">First</a>
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <a class="btn btn-outline-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% else %}
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Next</a>
            <a class="btn btn-outline-secondary disabled mb-4" href="#">Last</a>
        {% endif %}

    {% endif %}
{% endblock %}

viewer/templates/tournaments_index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<div class="center">
    <h1 style="color:white">Zagrajmy turniej!</h1>
    <button type="button" class="btn btn-secondary btn-lg" style="font-family:'Courier New'">Zaloguj</button>
    <button type="button" class="btn btn-secondary btn-lg" style="font-family:'Courier New'">Rejestracja</button>
</div></div>

{% endblock %}